// spotless:off
package frc.robot.generated.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftSecondSwipe = new ChoreoTraj(
        "LeftSecondSwipe",
        OptionalInt.empty(),
        8.52307,
        new Pose2d(3.796, 7.45338, Rotation2d.fromRadians(0)),
        new Pose2d(0.70485, 5.96329, Rotation2d.fromRadians(-3.14159))
    );
    public static final ChoreoTraj LeftStartSwipe = new ChoreoTraj(
        "LeftStartSwipe",
        OptionalInt.empty(),
        5.14744,
        new Pose2d(4.05, 7.45338, Rotation2d.fromRadians(3.14159)),
        new Pose2d(3.796, 7.45338, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj LeftTrenchToDepot = new ChoreoTraj(
        "LeftTrenchToDepot",
        OptionalInt.empty(),
        2.61685,
        new Pose2d(4.05, 7.45338, Rotation2d.fromRadians(3.14159)),
        new Pose2d(0.70485, 5.96328, Rotation2d.fromRadians(3.14159))
    );
    public static final ChoreoTraj RightSecondSwipe = new ChoreoTraj(
        "RightSecondSwipe",
        OptionalInt.empty(),
        5.82499,
        new Pose2d(3.796, 0.61595, Rotation2d.fromRadians(0)),
        new Pose2d(2.90337, 1.19646, Rotation2d.fromRadians(-2.79936))
    );
    public static final ChoreoTraj RightStartSwipe = new ChoreoTraj(
        "RightStartSwipe",
        OptionalInt.empty(),
        5.14744,
        new Pose2d(4.05, 0.61595, Rotation2d.fromRadians(3.14159)),
        new Pose2d(3.796, 0.61595, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj ShortLeftSecondSwipe = new ChoreoTraj(
        "ShortLeftSecondSwipe",
        OptionalInt.empty(),
        8.06641,
        new Pose2d(3.796, 7.45338, Rotation2d.fromRadians(0)),
        new Pose2d(0.70485, 5.96329, Rotation2d.fromRadians(-3.14159))
    );
    public static final ChoreoTraj ShortLeftStartSwipe = new ChoreoTraj(
        "ShortLeftStartSwipe",
        OptionalInt.empty(),
        5.14744,
        new Pose2d(4.05, 7.45338, Rotation2d.fromRadians(3.14159)),
        new Pose2d(3.796, 7.45338, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj AvoidanceLeftStartSwipe = new ChoreoTraj(
        "AvoidanceLeftStartSwipe",
        OptionalInt.empty(),
        5.04635,
        new Pose2d(4.05, 7.45338, Rotation2d.fromRadians(-3.14159)),
        new Pose2d(3.796, 7.45338, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("LeftSecondSwipe", LeftSecondSwipe),
        Map.entry("LeftStartSwipe", LeftStartSwipe),
        Map.entry("LeftTrenchToDepot", LeftTrenchToDepot),
        Map.entry("RightSecondSwipe", RightSecondSwipe),
        Map.entry("RightStartSwipe", RightStartSwipe),
        Map.entry("ShortLeftSecondSwipe", ShortLeftSecondSwipe),
        Map.entry("ShortLeftStartSwipe", ShortLeftStartSwipe),
        Map.entry("AvoidanceLeftStartSwipe", AvoidanceLeftStartSwipe)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
